### ISSUE TITLE
Tabela "Order" não sendo cadastrada

### ISSUE THREAD

**Issue by Pliavi** [lucasvenez/ormclass#2]
O problema verificado sobre a tabela _ORDER_ não era apenas por ter os nomes `date` e `time` que são palavras reservadas do MariaDB, mas `ORDER` também é uma palavra reservada (`ORDER BY`, nem tinha lembrado 😫 ) e isso faz com que a tabela não seja cadastrada.
Existem 2 formas de corrigir:
- Trocando o nome da classe para uma palavra livre (Não recomendado);
- Adicionando a referência a tabela utilizando crase na _Annotation_ 
  `@Table(name = "`Order`")`

**Comment by lucasvenez** [comment]
Olá @Pliavi,

Muito bem observado. A última solução é a mais adequada e também poderia ser aplicada para o problema encontrado no nome das colunas date e time.
