### ISSUE TITLE
Problema com cadastro "automático" de produtos via Order

### ISSUE THREAD

**Issue by Pliavi** [lucasvenez/ormclass#4]
Não sei se o Hibernate não é capaz ou se deixei escapar alguma coisa, mas fiquei quebrando a cabeça ontem e não consegui descobrir o problema e fiquei com a dúvida:
Se cadastro um **Produto** em **ItemVenda** e **ItemVenda** em **Venda**, o produto também é persistido se persisto a venda¹?

Porque pelo que percebi o Hibernate chega a tentar fazer, mas como o Produto ainda não foi persistido, não tem um ID, logo no código ele recebe `null`, mas o próprio Hibernate proíbe ele de ser persistido por conter ID nulo, tentei trocar o tipo para `long`, mas caio em outro problema, ele tenta criar todos os produtos com ID 0, também não permitindo a persistência.

A única solução foi persistir os produtos antes de vinculá-los aos itemVenda, **mas queria não precisar fazer isso, existe esta possibilidade?**

Eis o fragmento com a forma que consegui:

``` Java
Order order = new Order(EasyDate.toDate(19,9,2016), EasyDate.timeToDate(14,30,12), eu);

// products first parameter is a quantity integer;
products.put(1, new Product("Whiskey BadHorse", 139.9d, drinkables));
products.put(2, new Product("Mortadela Pç. 500gr", 10d, new Category("Frios")));
products.put(5, new Product("Coca-Cola", 3d, drinkables));

products.forEach((quantity,product) -> productDAO.persist(product)); // I would like to remove this line;
products.forEach((quantity,product) -> order.addOrderItems(new OrderItem(order, product, quantity)));

orderDAO.persist(order);
```

**¹ até porque está com `CascadeType.PERSIST`**

**Comment by lucasvenez** [comment]
@Pliavi,

Verifique se a atualização que fiz ajuda a resolver esse problema. Existe a possibilidade de haver a necessidade de definir a annotation `@GeneratedValue(strategy=GenerationType.AUTO)` para os atributos auto-incremento.

Não fiz esse teste. Faça-o e tente inclusive outras estratégias para verificar. Mas o Hibernate consegue sim fazer essa persistência automática.

Atenciosamente,

**Comment by Pliavi** [comment]
Fiz o teste, ainda continua se m fazê-lo, não lembro se estava assim antes, mas sem persistir os produtos nada é persistido, porém não dá nenhum log de erro, na verdade o Hibernate nem mesmo chega a criar as queries de inclusão.

Pelo que está parecendo é algo entre o OrderItem e o Product, algum deles só está permitindo a criação se o Product for persistido. Ou em último caso a DAO (pouco provável).

Vou tentar ver se encontro algo, por enquanto está tudo correndo bem, fora essa parte.

== Edit == 22-09-2016 ==
**Nota Sobre a HashMap:** Antes de tentar qualquer coisa pensei que poderia ser minha hashmap que estivesse dando problema (por mais estranho que pudesse ser já que persistia manualmente, mas não custa nada testar).
O que acontecia era o seguinte: Se eu não persistia a venda e produto (ou seja, nada era pra ser cadastrado) a minha `Hash` continuava intacta, quando eu dava `persist` apenas na venda, ela ficava completamente nula, e como nota, era dado o print na `Hash` antes de dar o `persist`, e sem a DAO a `Hash` continuava inteira, algo na `OrderDAO` estava apagando minha `Hash` (bizarro, mas... Sei lá).

**Comment by Pliavi** [comment]
Não sei dizer o que exatamente foi o causador do problema, mas vamos contar uma historinha:

> Não sou muito fã de chave composta, me causa muita confusão (e deve ser mais custoso no ponto DesempenhoXEspaço)... Fim 😆

Então, nas tentativas de corrigir o problema pensei na possibilidade de remover a chave composta de `OrderItem` e criar uma chave primária própria, e não é que deu certo? Nada além disso foi alterado.

``` Java
    @Id
    @GeneratedValue
    private Integer idOrderItem;

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "idProduct", referencedColumnName="idProduct")
    private Product product;

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "idOrder", referencedColumnName="idOrder")
    private Order order;
```

**Nota Sobre a HashMap²:** Agora ao usar a _DAO_ e dar o _persist_ a _Hash_ se mantém íntegra, o problema é saber o porque ela apagava anteriormente.

**Comment by lucasvenez** [comment]
Olá @Pliavi,

Muito bom! Mas ainda precisamos encontrar uma solução para utilizar as chaves-compostas. Na realidade adicionar um atribuído auto-incremento extra e definir esse como chave-primária possui algumas vantagens, mas `there is no free lunch`.

O lado bom é a simplicidade. Isso é indiscutível. Mas os ônus são a falta de semântica agregada a esse novo atributo, ele poderia ser simplesmente removido sem nenhuma perda, e também a questão de espaço a ser utilizado.

Obviamente, indexar dois atributos aparenta ser mais custoso, mas nas implementações com tabelas de espalhamento isso não se aplicada. Keep studying!

**Comment by Pliavi** [comment]
Testei ambos os casos, com _Embedded_ e a classe para os _ID's_ e adicionar o _persist_ do produto na _OrderDAO_, resultados até então:

### Embeddable:
- **Descrição:** Continua não gerando as _querys_.
- **Commit:** 4bb5b04a808c7d0e694eb28598be8a8e14afb9d2

### Persist na OrderDAO:
- **Descrição:** Funcionando sem problemas, obviamente.
- **Commit:** bdcf03280485f5e710f75a6aaea9953a1f5a3522
